# C# / .NET
[[language]]
name = "c-sharp"
scope = "source.cs"
injection-regex = "c-?sharp"
file-types = ["cs", "csx"]
roots = ["*.csproj", "*.sln"]
language-servers = ["omnisharp"]
indent = { tab-width = 4, unit = "    " }
auto-format = true

[language-server.omnisharp]
command = "OmniSharp"
args = ["--languageserver", "--hostPID", "0"]

# TypeScript
[[language]]
name = "typescript"
scope = "source.ts"
injection-regex = "^(ts|typescript)$"
file-types = ["ts"]
language-servers = ["typescript-language-server"]
auto-format = true
indent = { tab-width = 2, unit = "  " }

# TSX (React)
[[language]]
name = "tsx"
scope = "source.tsx"
injection-regex = "^(tsx)$"
file-types = ["tsx"]
language-servers = ["typescript-language-server"]
auto-format = true
indent = { tab-width = 2, unit = "  " }

# JavaScript
[[language]]
name = "javascript"
scope = "source.js"
file-types = ["js", "jsx", "mjs"]
language-servers = ["typescript-language-server"]
auto-format = true
indent = { tab-width = 2, unit = "  " }

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]
config.hostInfo = "helix"

# CSS
[[language]]
name = "css"
scope = "source.css"
file-types = ["css"]
language-servers = ["vscode-css-language-server","tailwindcss-language-server"]
auto-format = true
indent = { tab-width = 2, unit = "  " }

[language-server.vscode-css-language-server]
command = "vscode-css-language-server"
args = ["--stdio"]
config.css.validate.enable = true
config.scss.validate.enable = true
config.less.validate.enable = true

# HTML (para templates)
[[language]]
name = "html"
scope = "text.html.basic"
file-types = ["html", "cshtml", "razor"]
language-servers = ["vscode-html-language-server"]
auto-format = true
indent = { tab-width = 2, unit = "  " }

[language-server.vscode-html-language-server]
command = "vscode-html-language-server"
args = ["--stdio"]

# Markdown
[[language]]
name = "markdown"
scope = "source.md"
file-types = ["md", "markdown"]
language-servers = ["marksman"]
auto-format = false
indent = { tab-width = 2, unit = "  " }

[language-server.marksman]
command = "marksman"
args = ["server"]

# JSON
[[language]]
name = "json"
scope = "source.json"
file-types = ["json"]
language-servers = ["vscode-json-language-server"]
auto-format = true
indent = { tab-width = 2, unit = "  " }

[language-server.vscode-json-language-server]
command = "vscode-json-language-server"
args = ["--stdio"]

